### ISSUE TITLE
Relevance of the rules

### ISSUE THREAD

**Issue by TLOshini** [ymoch/apyori#36]
Hi, 

Can I please know if the `rules` returned from the algorithm are sorted by any measure? Or if there's a method to retrieve the top-n most relevant rules?

**Comment by ymoch** [comment]
I'm sorry for my TOO LATE response...
Apyori has no methods to sort results. The major reason is that most of processes are lazily evaluated. You can sort them by native `sorted` method (note that `sorted` will buffer all items, which results in memory consumption).
