### ISSUE TITLE
antecedent and antecedant

### ISSUE THREAD

**Issue by aashishgahlawat** [ymoch/apyori#38]
If you run 

```
    from mlxtend.frequent_patterns import apriori
    from mlxtend.frequent_patterns import association_rules
    dataframe = apriori(dataframe, min_support=min_support, use_colnames=True)
    dataframe = association_rules(dataframe, metric="lift", min_threshold=min_threshold)
    dataframe['antecedents_length'] = dataframe['antecedents'].str.len()
    dataframe['consequents_length'] = dataframe['consequents'].str.len()
```
In pycharm sciView the column name in antecedEnt while in jupyter notebook name is antecedAnt, is the column name specific to platform? Obviously this breaks code. E and A varies. 
I ran exactly same code on same dataframe and got column names different

**Comment by ymoch** [comment]
I wonder if this issue is for another repository (https://github.com/rasbt/mlxtend).

**Comment by aashishgahlawat** [comment]
Yes, sorry!
