### ISSUE TITLE
RelationRecord输出格式是什么？

### ISSUE THREAD

**Issue by ZMK112** [ymoch/apyori#39]
![MP9WNMKX~4`Y`A7A26PRYLS](https://user-images.githubusercontent.com/24214864/54893866-d3901c80-4ef2-11e9-8a93-5391a075e063.png)
您好，这个仓库很棒，但就是输出格式完全看不懂，ordered_statistics.......这是什么意思啊？

**Comment by ymoch** [comment]
Sorry for my late response...
`Support`, `confidence` and `lift` are general concepts in [association rule learnings](https://en.wikipedia.org/wiki/Association_rule_learning).
